# --- Étape 1 : Build de l'application React ---
FROM node:20-alpine AS build

# Créer le dossier de travail
WORKDIR /app

# Copier package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier tout le reste du projet
COPY . .

# Build de l'application
RUN npm run build

# --- Étape 2 : Serveur Nginx pour production ---
FROM nginx:alpine

# Copier le build React vers le dossier par défaut Nginx
COPY --from=build /app/build /usr/share/nginx/html

# Supprimer le default.conf
RUN rm /etc/nginx/conf.d/default.conf

# Copier notre propre configuration Nginx
COPY nginx.conf /etc/nginx/conf.d

# Exposer le port 80
EXPOSE 80

# Démarrer Nginx
CMD ["nginx", "-g", "daemon off;"]
